name: Build ISO VoidLinux

# Gatilhos para o workflow
on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - "ISO-*"
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: "Name for the ISO"
        required: true
        default: "VOID_LIVE"
      edition:
        type: choice
        description: "Edition"
        options:
          - base-custom
          - xfce-custom
          - awesome
          - enlightnment
          - fluxbox
          - gnome
          - kde
          - all X
        default: "XFCE CUSTOM"
      tmate:
        type: boolean
        description: "Enable debugging with tmate"
        required: false
        default: false

  schedule:
    - cron: "0 6 * * *" # Roda todo dia às 06:00 UTC
    - cron: "0 18 * * 5" # Roda toda sexta-feira às 18:00 UTC

# Jobs do workflow
jobs:
  # Job para obter a hora atual
  get-time:
    runs-on: ubuntu-latest
    outputs:
      time: ${{ steps.time.outputs.time }} # Saída do job
    steps:
      - name: Obter a hora atual
        id: time
        run: echo "::set-output name=time::$(date +'%Y.%m.%d-%H%M')"

  # Job para definir o nome do repositório
  set-repo-name:
    runs-on: ubuntu-latest
    outputs:
      REPOSITORY_NAME: ${{ steps.get-repo-name.outputs.repo_name }}
    steps:
      - name: Obter nome do repositório
        id: get-repo-name
        #run: echo "repo_name=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_OUTPUT
        run: echo "::set-output name=repo_name::$(basename $GITHUB_REPOSITORY)"

  build:
    name: Build void-x86_64-${{ github.event.client_payload.edition || 'base-custom' }}
    runs-on: ubuntu-latest
    needs: [get-time, set-repo-name] # Depende do job get-time para obter a hora atual e do job set-repo-name para obter o nome do repositório
    env:
      REPO_NAME: ${{ needs.set-repo-name.outputs.REPOSITORY_NAME }} # Acesso à variável de ambiente definida no job anterior
    container:
      image: vcatafesta/voidlinux-docker:latest
      options: --privileged
    #      volumes:
    #        - /mnt/var_lib_manjaro_tools_buildiso:/var/lib/manjaro-tools/buildiso
    #        - /mnt/var_cache_manjaro_tools_iso:/var/cache/manjaro-tools/iso

    steps:
      #      - name: Set up volume directory on HOST
      #        run: |
      #          mkdir -p /mnt/var_lib_manjaro_tools_buildiso
      #          mkdir -p /mnt/var_cache_manjaro_tools_iso

      - name: Install Required Libraries
        run: |
          xbps-install -Syu -f \
            xbps \
            xtools \
            bash \
            sudo \
            openssh \
            tmate \
            xz \
            zip \
            kmod \
            ncurses \
            which \
            vpm \
            libstdc++ \
            vim \
            nano \
            curl \
            git \
            bash \
            tree \
            duf \
            gettext \
            rsync \
            util-linux \
            coreutils \
            sed \
            grep \
            btrfs-progs \
            e2fsprogs \
            exfatprogs \
            dosfstools \
            xfsprogs

      - name: Create user builduser
        run: |
          useradd -m -G wheel,audio,video,cdrom,optical,kvm,xbuilder builduser

      - name: Display the current user in container
        run: |
          echo "#########################################"
          echo "Current container is: $(hostname)"
          echo "Current user is: $(whoami)"
          echo "Current user ID is: $(id -u)"
          echo "Current user details:"
          id
          echo "#########################################"
          df -hT
          echo "#########################################"
          ls -la /mnt
          echo "#########################################"

      - name: Initial Debug
        run: |
          echo "Workflow started"
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Action: ${{ github.event.action }}"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build ISO
        uses: ./
        id: build
        with:
          name: ${{ github.event.client_payload.name || inputs.name }}
          edition: ${{ github.event.client_payload.edition || inputs.edition }}
          release_tag: ${{ github.event.client_payload.release_tag || inputs.release_tag }}
          kernel: ${{ github.event.client_payload.kernel || inputs.kernel }}
          scope: ${{ github.event.client_payload.scope || inputs.scope }}
          office-chooser: ${{ github.event.client_payload.office-chooser || inputs.office-chooser }}

          # Parâmetros de branches
          manjaro_branch: ${{ github.event.client_payload.manjaro_branch || inputs.manjaro_branch }}
          community_branch: ${{ github.event.client_payload.community_branch || inputs.community_branch }}
          biglinux_branch: ${{ github.event.client_payload.biglinux_branch || inputs.biglinux_branch }}

          # Depuração
          tmate: ${{ github.event.client_payload.tmate || 'false' }}

          # Tokens e segredos
          github_token: ${{ secrets.ORGANIZATION_TOKEN }}

      - name: Calculate MD5 Hash of files
        shell: bash
        run: |
          pushd "${{ env.WORK_PATH }}"
          echo "Calculating MD5 hash for: ${{ env.ISO_FULLNAME }} file..."
          echo "ISO_BASENAME is: '${{ env.ISO_BASENAME }}'"
          if [[ -f "${{ env.ISO_BASENAME }}" ]]; then
            md5sum "${{ env.ISO_BASENAME }}" > "${{ env.ISO_BASENAME }}.md5"
            echo "MD5 '$ISO_BASENAME.md5' hash calculated and saved:"
            cat "${{ env.ISO_BASENAME }}.md5"
          else
            echo "ERRO: ${{ env.ISO_BASENAME }} file not found at ${{ env.WORK_PATH }}"
            exit 1
          fi
          popd

      - name: Prepare ISO file for release
        id: prepare-iso
        shell: bash
        run: |
          ls -lha
          release=${{ env.ISO_BASENAME }} # Apenas obtém o nome do arquivo com extensão
          release="${release%.iso}"
          echo "release_name=${release}" >> $GITHUB_ENV
          if zip \
              --junk-paths \
              --store \
              -s 2000m \
              ${release}.zip \
              ${{ env.ISO_FULLNAME }} \
              ${{ env.ISO_FULLNAME }}.md5; then
            echo "ISO_FULLNAME=${{ env.WORK_PATH }}/${release}.iso" >> "$GITHUB_ENV"
            echo "ISO_BASENAME=${release}.iso"                      >> "$GITHUB_ENV"
            echo "${ISO_FULLNAME} prepared for release"
            ls -lha
          else
            echo "ERRO: No preparo do arquivo ISO para release"
            exit 1
          fi

      - name: Debug environment variables and List Files
        run: |
          echo "ISO_BASENAME=${{ env.ISO_BASENAME }}"
          echo "ISO_FULLNAME=${{ env.ISO_FULLNAME }}"
          echo "ISO Path from output=${{ steps.define-paths.outputs.iso_path }}"
          ls -lah "${{ env.WORK_PATH }}"

      - name: Upload FILES as artifact
        uses: actions/upload-artifact@v3
        env:
          GITHUB_TOKEN: ${{ secrets.ORGANIZATION_TOKEN }}
        with:
          name: ${{ env.ISO_BASENAME }}
          path: |
            ${{ env.ISO_FULLNAME }}
            ${{ env.ISO_FULLNAME }}
            ${{ env.ISO_FULLNAME }}.md5
          if-no-files-found: warn
          include-hidden-files: false

      - name: Criar release iso
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ORGANIZATION_TOKEN }}
        with:
          tag_name: ${{ env.ISO_TAG_NAME }}
          release_name: Release ${{ env.ISO_TAG_NAME }}
          body: |
            - **Data e Hora        :** ${{ needs.get-time.outputs.time }}
            - **Nome do Repositório:** ${{ env.REPO_NAME }}
          draft: false
          prerelease: false

      - name: Fazer upload do arquivo .iso no release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ORGANIZATION_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # URL gerada no passo da criação da release
          asset_path: ${{ env.ISO_FULLNAME }} # Caminho do arquivo .iso
          asset_name: ${{ env.REPO_NAME }}.zip
          asset_content_type: application/iso # Tipo correto para arquivos .iso

      - name: Verificar arquivo .iso
        run: ls -lh ${{ env.ISO_FULLNAME }} # Verifique se o arquivo .iso foi gerado corretamente

      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 65002 ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Enviar arquivo ISO para o servidor via SCP com porta customizada
        run: |
          scp -P 65002 ${{ env.ISO_FULLNAME }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/u537062342/void/current
